RedHatInsights/ccx-notification-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/ccx-notification-writer:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/ccx-upgrades-data-eng:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/ccx-upgrades-inference:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/content-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/data-pipeline:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-ccx-messaging:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-content-template-renderer:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-core-messaging:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

# RedHatInsights/insights-data-schemas:
#   - CODEOWNERS

# RedHatInsights/insights-on-prem:
#   - CODEOWNERS

RedHatInsights/insights-operator-gathering-conditions:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-operator-gathering-conditions-service:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-operator-utils:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-results-aggregator:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-results-aggregator-cleaner:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

# RedHatInsights/insights-results-aggregator-data:
#   - CODEOWNERS

RedHatInsights/insights-results-aggregator-exporter:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-results-aggregator-mock:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-results-aggregator-utils:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

# RedHatInsights/insights-results-mcp:
#   - CODEOWNERS

RedHatInsights/insights-results-smart-proxy:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/obsint-mocks:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/parquet-factory:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml

RedHatInsights/insights-behavioral-spec:
  - CODEOWNERS
  - renovate.json
  - source: workflows_examples/linters.yaml
    dest: .github/workflows/linters.yaml
  - source: workflows_examples/bots-auto-merge.yaml
    dest: .github/workflows/bots-auto-merge.yaml
