# Set as automatically merge all the pull requests created by bots

name: Bots auto-merge
on:
  workflow_call:
    secrets:
      OBSINT_PROCESSING_APP_CLIENT_ID:
        required: true
      OBSINT_PROCESSING_APP_PRIVATE_KEY:
        required: true

  pull_request:

jobs:
  bots-automerge:
    runs-on: ubuntu-latest
    if: |
      (
        github.event.pull_request.user.login == 'obsint-processing-app[bot]' &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:
      - id: app_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.OBSINT_PROCESSING_APP_CLIENT_ID }}
          private-key: ${{ secrets.OBSINT_PROCESSING_APP_PRIVATE_KEY }}

      - name: Enable auto-merge for PR
        run: gh pr merge --auto --merge "${PR_URL}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
